name: Optimize CSS

on:
  push:
    paths:
      - Forest.css
  pull_request:
    paths:
      - Forest.css

jobs:
  optimize-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install cssnano postcss-cli csso-cli

      - name: Optimize CSS
        run: |
          postcss Forest.css \
            -o Forest.min.css \
            --use cssnano \
            --no-map
          csso Forest.min.css \
            -o Forest.min.css \
            --restructure-off

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Forest.min.css
          git commit -m "Optimize and compress CSS file"
          git push origin ${{ github.ref }}
