name: Optimize CSS

on:
  push:
    branches: [ master ]
    paths:
      - 'Forest.css'

jobs:
  optimize-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install cssnano postcss-cli csso-cli
      - name: Optimize CSS
        run: |
          postcss Forest.css -o Forest.min.css --use cssnano --no-map
          csso Forest.min.css -o Forest.min.css --restructure-off
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add Forest.min.css
          git commit -m "Optimize CSS"
          git push
